apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: cat-website-app-intel
        image: climacs/cat-website-app-intel
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp-test
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
