apiVersion: v1
kind: Secret
metadata:
  name: selfsigned-cert-tls
  namespace: myapp-test
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded cert>
  tls.key: <base64 encoded key>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: cat-website-app-intel
        image: climacs/cat-website-app-intel
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp-test
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - myapp.example.com
    secretName: selfsigned-cert-tls
  rules:
  - host: myapp.example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp-service
            port:
              number: 80
